
var DECKS_LIST = [
  {
    "name":"Kimoto",
    "cards":[
      { "type": "Deck", "name":"Punishment of the Retro Guard", "amount":3},
      { "type": "Deck", "name":"kimoto_fierce_dragon", "amount":2},
      { "type": "Deck", "name":"Kimoto Wise Frog", "amount":2},
      { "type": "Deck", "name":"Kimoto Vengeance", "amount":3},
      { "type": "Deck", "name":"Kimoto Sweet Genie", "amount":3},
      { "type": "Deck", "name":"Kimoto Support Slime", "amount":2},
      { "type": "Deck", "name":"Kimoto Spear Racoon", "amount":2},
      { "type": "Deck", "name":"Kimoto Realm", "amount":3},
      { "type": "Deck", "name":"Kimoto Prime Discipels", "amount":2},
      { "type": "Deck", "name":"Kimoto Prime Ape", "amount":2},
      { "type": "Deck", "name":"Kimoto Nursing", "amount":3},
      { "type": "Deck", "name":"Kimoto Lazy Oatzel", "amount":2},
      { "type": "Deck", "name":"Kimoto Lantern Girl", "amount":2},
      { "type": "Deck", "name":"Kimoto Fat Twin Dragons", "amount":2},
      { "type": "Deck", "name":"Kimoto Elegant Bark", "amount":2},
      { "type": "Deck", "name":"Kimoto Crystal Ghost", "amount":3},
      { "type": "Deck", "name":"Kimoto Cursed King", "amount":2},
      { "type": "Deck", "name":"Big Lovely Family", "amount":3},
      { "type": "Deck", "name":"Ancient Waboku", "amount":3},
    ]
  },
  {
    "name":"Cyberdark",
    "cards":[
      { "type": "Deck", "name":"Cyberdark Edge", "amount":3},
      { "type": "Deck", "name":"Cyberdark Horn", "amount":3},
      { "type": "Deck", "name":"Cyberdark keel", "amount":3},
      { "type": "Deck", "name":"Cyberdark Cannon", "amount":3},
      { "type": "Deck", "name":"Cyberdark Claw", "amount":3},
      { "type": "Deck", "name":"Cyberdark Impact", "amount":2},
      { "type": "Deck", "name":"Cyberdark Inferno", "amount":2},
      { "type": "Deck", "name":"Shaddoll Hedgehog", "amount":2},
      { "type": "Deck", "name":"Shadoll Dragon", "amount":2},
      { "type": "Deck", "name":"Shadoll Squamata", "amount":2},
      { "type": "Deck", "name":"Shaddoll Fusion", "amount":2},
      { "type": "Deck", "name":"Schaddoll Schism", "amount":1},
      { "type": "Deck", "name":"Future Fusion", "amount":3},
      { "type": "Deck", "name":"Monster Reborn", "amount":1},
      { "type": "Deck", "name":"Dogmatika Maximus", "amount":2},
      { "type": "Deck", "name":"Nadir Servant", "amount":3},
      { "type": "Deck", "name":"Call of the Haunted", "amount":1},
      { "type": "Deck", "name":"metaverse", "amount":1},
      { "type": "Deck", "name":"Super Polymerizzation", "amount":2},
      { "type": "Deck", "name":"Limiter Removal", "amount":1},
      { "type": "Extra Deck", "name":"Cyberdark Dragon", "amount":2},
      { "type": "Extra Deck", "name":"Cyberdarkness Dragon", "amount":2},
      { "type": "Extra Deck", "name":"el-shaddoll-winda", "amount":2},
      { "type": "Extra Deck", "name":"El Shaddoll Construct", "amount":1},
      { "type": "Extra Deck", "name":"El Shaddoll Apkallone", "amount":1},
      { "type": "Extra Deck", "name":"Five-Headed Dragon", "amount":2},
      { "type": "Extra Deck", "name":"PSY-Framelord Omega", "amount":1},
      { "type": "Extra Deck", "name":"Starving Venom Fusion Dragon", "amount":1},
      { "type": "Extra Deck", "name":"Predaplant Chimerafflesia", "amount":1},
      { "type": "Extra Deck", "name":"Elder Entity ntess", "amount":2},
    ]
  },
  {
    "name":"Orichalcos",
    "cards":[
      { "type": "Deck", "name":"orichalcos_magician_apprendice", "amount":2},
      { "type": "Deck", "name":"Terror of Atlantis", "amount":1},
      { "type": "Deck", "name":"burning_will_for_the_seal", "amount":2},
      { "type": "Deck", "name":"arrogance_of_orichalcos", "amount":2},
      { "type": "Deck", "name":"attack_guidance_barrier", "amount":2},
      { "type": "Deck", "name":"call_of_the_orichalcos_servant", "amount":2},
      { "type": "Deck", "name":"divine_basilisk_geh", "amount":1},
      { "type": "Deck", "name":"eternal_divine_wrath", "amount":1},
      { "type": "Deck", "name":"impudence_of_orichalcos", "amount":2},
      { "type": "Deck", "name":"light_barrier_of_the_stolen_souls", "amount":2},
      { "type": "Deck", "name":"mirror_knight_calling", "amount":1},
      { "type": "Tokens", "name":"mirror_knight_token", "amount":4},
      { "type": "Deck", "name":"orichalcos_aristeros", "amount":1},
      { "type": "Deck", "name":"orichalcos_dexia", "amount":1},
      { "type": "Deck", "name":"orichalcos_deuteros", "amount":1},
      { "type": "Deck", "name":"orichalcos_gigas", "amount":1},
      { "type": "Deck", "name":"orichalcos_kiseichu", "amount":1},
      { "type": "Deck", "name":"orichalcos_kynerza", "amount":2},
      { "type": "Deck", "name":"orichalcos_malevolence", "amount":2},
      { "type": "Deck", "name":"orichalcos_kyutora", "amount":1},
      { "type": "Deck", "name":"orichalcos_magic_stone", "amount":2},
      { "type": "Deck", "name":"orichalcos_magician", "amount":2},
      { "type": "Deck", "name":"orichalcos_magician_girl", "amount":2},
      { "type": "Deck", "name":"orichalcos_magnetia", "amount":2},
      { "type": "Deck", "name":"orichalcos_matia", "amount":2},
      { "type": "Deck", "name":"orichalcos_mirror", "amount":1},
      { "type": "Deck", "name":"orichalcos_punos", "amount":2},
      { "type": "Deck", "name":"orichalcos_shunoros", "amount":1},
      { "type": "Deck", "name":"orichalcos_tritos", "amount":1},
      { "type": "Deck", "name":"sword_of_sealing", "amount":2},
      { "type": "Tokens", "name":"sentinel_token", "amount":9},
      { "type": "Deck", "name":"the_seal_of_orichalcos", "amount":1},
      { "type": "Extra Deck", "name":"sealed_sacred_tree", "amount":2},
      { "type": "Extra Deck", "name":"orichalcos_true_form", "amount":1},
      { "type": "Extra Deck", "name":"orichalcos_talisman_trader", "amount":1},
      { "type": "Extra Deck", "name":"orichalcos_last_defender", "amount":2},
      { "type": "Extra Deck", "name":"orichalcos_golem", "amount":2},
      { "type": "Extra Deck", "name":"orichalcos_eva", "amount":1},
      { "type": "Extra Deck", "name":"gizonda_curse_of_the_diferent_dimention", "amount":1},
      { "type": "Extra Deck", "name":"fossil_dragon_orichalcos", "amount":1},
      { "type": "Extra Deck", "name":"orichalcos_ancient_soldier", "amount":1},
      { "type": "Extra Deck", "name":"orichalcos_chimera_blaze", "amount":2},
      { "type": "Extra Deck", "name":"levonia_the_orichalcos_chaos_prince", "amount":1},
    ]
  },
  {
    "name":"Blue Eyes White Dragon",
    "cards":[
      { "type": "Deck", "name":"Deep eyes white dragon", "amount":2},
      { "type": "Deck", "name":"Blue eyes white dragon", "amount":3},
      { "type": "Deck", "name":"Blue-Eyes Alternative White Dragon", "amount":3},
      { "type": "Deck", "name":"Blue-Eyes Abiss Dragon", "amount":2},
      { "type": "Deck", "name":"Dragon spirit of white", "amount":1},
      { "type": "Deck", "name":"The White Stone of Ancients", "amount":3},
      { "type": "Deck", "name":"The White Stone of Legend", "amount":2},
      { "type": "Deck", "name":"Sage with Eyes of Blue", "amount":3},
      { "type": "Deck", "name":"Return of the Dragon Lords", "amount":3},
      { "type": "Deck", "name":"Polymerization", "amount":2},
      { "type": "Deck", "name":"Pot of Desires", "amount":2},
      { "type": "Deck", "name":"Trade in", "amount":2},
      { "type": "Deck", "name":"Cards of Consonance", "amount":2},
      { "type": "Deck", "name":"Dragon Shrine", "amount":3},
      { "type": "Deck", "name":"The Melody of Awakening Dragon", "amount":3},
      { "type": "Deck", "name":"Mystical space typhoon", "amount":2},
      { "type": "Deck", "name":"Silver's Cry", "amount":2},
      { "type": "Extra Deck", "name":"Blue eyes alternative ultimate dragon", "amount":1},
      { "type": "Extra Deck", "name":"Neo Blue-Eyes Ultimate Dragon", "amount":1},
      { "type": "Extra Deck", "name":"Blue-Eyes Twin Burst Dragon", "amount":2},
      { "type": "Extra Deck", "name":"Azure eyes silver dragon", "amount":2},
      { "type": "Extra Deck", "name":"Blue-Eyes Spirit Dragon", "amount":2},
      { "type": "Extra Deck", "name":"Shooting Riser Dragon", "amount":1},
      { "type": "Extra Deck", "name":"Number 46 Dragluon", "amount":1},
      { "type": "Extra Deck", "name":"Galaxy-Eyes Cipher Blade Dragon", "amount":1},
      { "type": "Extra Deck", "name":"Galaxy-Eyes Full Armor Photon Dragon", "amount":1},
      { "type": "Extra Deck", "name":"Galaxy-Eyes Cipher Dragon", "amount":1},
      { "type": "Extra Deck", "name":"Number 38 Hope Harbinger Dragon Titanic Galaxy", "amount":1},
      { "type": "Extra Deck", "name":"Linkuriboh", "amount":1},
    ]
  },
  {
    "name":"Red Eyes Black Dragon",
    "cards":[
      { "type": "Deck", "name":"dark_magician", "amount":2},
      { "type": "Deck", "name":"red_eyes_black_dragon", "amount":3},
      { "type": "Deck", "name":"red_eyes_darkness_metal_dragon", "amount":1},
      { "type": "Deck", "name":"red_eyes_alternative_black_dragon", "amount":3},
      { "type": "Deck", "name":"tenyi_spirit_vishuda", "amount":3},
      { "type": "Deck", "name":"red_eyes_retro_dragon", "amount":2},
      { "type": "Deck", "name":"red_eyes_baby_dragon", "amount":2},
      { "type": "Deck", "name":"black_metal_dragon", "amount":3},
      { "type": "Deck", "name":"the_black_stone_of_legend", "amount":3},
      { "type": "Deck", "name":"red_eyes_fusion", "amount":3},
      { "type": "Deck", "name":"cards_of_the_red_stone", "amount":3},
      { "type": "Deck", "name":"the_claws_of_hermos", "amount":2},
      { "type": "Deck", "name":"inferno_fire_blast", "amount":3},
      { "type": "Deck", "name":"red_eyes_insight", "amount":3},
      { "type": "Deck", "name":"red_eyes_spirit", "amount":3},
      { "type": "Deck", "name":"red_eyes_fang_with_chain", "amount":3},
      { "type": "Deck", "name":"return_of_the_red_eyes", "amount":3},
      { "type": "Deck", "name":"red_eyes_burn", "amount":2},
      { "type": "Deck", "name":"eternal_soul", "amount":1},
      { "type": "Extra Deck", "name":"meteor_black_comet_dragon", "amount":1},
      { "type": "Extra Deck", "name":"red_eyes_dark_dragoon", "amount":2},
      { "type": "Extra Deck", "name":"red_eyes_black_dragon_sword", "amount":2},
      { "type": "Extra Deck", "name":"red_eyes_flare_metal_dragon", "amount":2},
      { "type": "Extra Deck", "name":"mecha_phantom_beast_dracossack", "amount":1},
      { "type": "Extra Deck", "name":"number_11_big_Eye", "amount":1},
      { "type": "Extra Deck", "name":"saryuja_skull_dread", "amount":1},
      { "type": "Extra Deck", "name":"darkness_metal_the_dragon_of_dark_steel", "amount":1},
      { "type": "Extra Deck", "name":"bujinki_ahashima", "amount":1},
      { "type": "Extra Deck", "name":"wee_witchs_apprentice", "amount":1},
      { "type": "Extra Deck", "name":"Union Carrier", "amount":1},
      { "type": "Extra Deck", "name":"relinquished_anima", "amount":1},
    ]
  }
];



function getDeckList(){
  DECKS_LIST.sort((a,b)=>{
    if(a["name"] < b["name"]){ return -1;}
    if(a["name"] > b["name"]){ return 1;}
    return 0;
  });
  return DECK_LIST;
}
